
version: '3.9'
services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/jobtracker
      - JWT_SECRET=supersecret
    depends_on: [mongo]

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes: ["./frontend:/app"]
    command: sh -c "npm install && npm run dev"
    ports: ["3000:5173"]
    depends_on: [backend]

  mongo:
    image: mongo:6
